version: "3.9"

services:
  server:
    image: user-service-image
    container_name: server
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
    external: true

