# NodeJS Version 16
FROM node:16.18-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

ARG ENV_FILE=.env.production.local

COPY $ENV_FILE .env.production.local

# Set Env
ENV NODE_ENV production

ENV LOG_DIR ../logs
# ARG ENV_FILE
# COPY $ENV_FILE /usr/src/app/.env

EXPOSE 3000

# Cmd script
CMD ["npm", "run", "start"]
